# Generated by Django 5.0.2 on 2024-05-24 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
